name: CI

on:
  push:
    branches:
      - main
      - next
  pull_request:

jobs:
  lint:
    name: Quality checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Security audit
        run: npm audit

      - name: Code coverage
        run: npx nyc --reporter=lcovonly npm test

      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true

      - name: Lint
        run: npx eslint .

      - name: Check formatting
        run: npx prettier . --check

  test:
    name: Test - ${{ matrix.os }} - Node v${{ matrix.node-version }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Git
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
